name: Assign Copilot to Issues

on:
  issues:
    types: [opened]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install node-fetch@2
      - run: node .github/scripts/assign-copilot.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name || github.repository.split('/')[1] }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}