name: Auto Assign Issues to Copilot

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Assign issue to copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            
            try {
              // Assign the issue to copilot
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number,
                assignees: ['copilot']
              });
              
              console.log(`✅ Successfully assigned issue #${issue_number} to copilot`);
              
              // Add a comment to confirm auto-assignment
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: '🤖 This issue has been automatically assigned to @copilot for review.'
              });
              
            } catch (error) {
              console.error('❌ Error assigning issue:', error.message);
              
              // If assignment fails, add a comment explaining the issue
              if (error.status === 422) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: '⚠️ Auto-assignment to @copilot failed. Please check if the user has access to this repository.'
                });
              }
            }
